### ISSUE TITLE
General way to override the spacing between blocks

### ISSUE THREAD

**Issue by iKlsR** [notionblog/vue-notion-render#2]
Would be nice if there were some quick and easy way to do this so the component can flow more text like without being line after line. Maybe a prop spacing `[block, prose']` etc... where normal text just flows and other block elements like list items remain normally as an idea, not sure how best to approach this but it would just be nice to at least control the block spacing.

Very useful library, thanks! Came in super handy as we use Notion as our wiki backend. 🙏

**Comment by yudax42** [comment]
Hello @iKlsR!

Actually, you can do it using Column List and customize the structure of your blocks from Notion. 
Here is How 👇
![fix](https://user-images.githubusercontent.com/75418209/128631646-7a38eca5-eacd-4d86-b044-d065f94d3551.gif)

Thank you for using this package!

**Comment by iKlsR** [comment]
Thanks for the reply, this isn't feasible for blocks of text and there are still gaps in the data. What I really wanted was a quick way to change this

> Lorem ipsum
>
> Another lorem line

into this

> Lorem ipsum
> Another lorem line

Update: I just got some time to really peek at the src and what I was looking for is a way to remove or edit the [`margin-bottom`](https://github.com/notionblog/vue-notion-render/search?q=margin-bottom). Since it's scoped and there are no class names after build that means I can't override it.

**Comment by yudax42** [comment]
Hello @iKlsR,
I'm sorry for the misunderstanding, I will fix it as soon as possible.
Thank You!
